# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: deploy to prod
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{ secrets.DEPLOY_DIR }}
            composer update
            vendor/bin/drush cache:rebuild
            vendor/bin/drush config:import -y
            vendor/bin/drush updatedb -y
            vendor/bin/drush cache:rebuild
          host: ${{ secrets.HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.PRIVATE_KEY}}
      
